services:
  nginx:
    container_name: dngfl-nginx
    build:
      context: ./nginx
      args:
        APP: litegen
    env_file:
      - ../.env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - litegen

  litegen:
    build:
      context: ../
      dockerfile: containers/Dockerfile
    container_name: litegen-app-container
    env_file:
      - ../.env.prod
    ports:
      - 8000:8000
    restart: "no"
