// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiCrawlCreateCrawlData, ApiCrawlCreateCrawlErrors, ApiCrawlCreateCrawlResponses, ApiCrawlListCrawlsData, ApiCrawlListCrawlsErrors, ApiCrawlListCrawlsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * ListCrawls
 */
export const apiCrawlListCrawls = <ThrowOnError extends boolean = false>(options?: Options<ApiCrawlListCrawlsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiCrawlListCrawlsResponses, ApiCrawlListCrawlsErrors, ThrowOnError>({
        url: '/api/crawl',
        ...options
    });
};

/**
 * CreateCrawl
 */
export const apiCrawlCreateCrawl = <ThrowOnError extends boolean = false>(options: Options<ApiCrawlCreateCrawlData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiCrawlCreateCrawlResponses, ApiCrawlCreateCrawlErrors, ThrowOnError>({
        url: '/api/crawl',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
